GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI2NmM1MzAxNzE3Mjg3MDkwNzE0MDZiNjEiLCJpYXQiOjE3MjQyMjM5NTAsImV4cCI6MTcyNDIyNzU1MH0.lZrQGmzyzJlEXJ69EDosdEbiSnHOe03sUmhbrDPvpdQ

{
  "title": "New wars",
  "author": "Kiran Krishna N",
  "url": "http://blog.cleancoder.com/uncle-bob/2",
  "likes": 2,
  "userId": "66c530171728709071406b61"
}

###
DELETE http://localhost:3003/api/blogs/66c500d482acb516280e54f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YzRkMzM2MjUwMzUyMmJiMzg2ZTIwMiIsImlhdCI6MTcyNDE4NTkxMX0.zrSAC0sxWn59FjUitlJ2oU9fngG2NiGNVisYOOuJ7f0

###
PUT http://localhost:3003/api/blogs/66c4f4a576fff98554232eb6
Content-Type: application/json

{
  "title": "Type sajhdgasjhd"
}